version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: always
    user: root
    ports:
      - 5678:5678
    environment:
        SET_CONTAINER_TIMEZONE: 'true'
        CONTAINER_TIMEZONE: America/Santiago
        GENERIC_TIMEZONE: America/Santiago
        TZ: America/Santiago    
        # N8N_HOST: ${SUBDOMAIN}.${DOMAIN_NAME}
        N8N_PORT: 5678
        # N8N_PROTOCOL: https
        NODE_ENV: production
        # WEBHOOK_URL: https://${SUBDOMAIN}.${DOMAIN_NAME}/
        # GENERIC_TIMEZONE: ${GENERIC_TIMEZONE}
    volumes:
      - ./n8n_data:/root/.n8n/

volumes:
  n8n_data:
    external: true